version: '3'
services:
  dj-musician:
    build:
      context: .
      target: musician
    volumes:
      - '.:/workspace:cached'
    command: sleep infinity # Se usa para evitar que el contenedor se cerre
    links:
      - dj-orchestra
  dj-orchestra:
    build:
      context: .
      target: orchestra
    volumes:
      - '.:/workspace:cached'
    command: sleep infinity # Se usa para evitar que el contenedor se cerre
    

