# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-03-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import orchestra.contrib.domains.validators


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_auto_20200204_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='min_ttl',
            field=models.CharField(blank=True, help_text='The minimum time-to-live value applies to all resource records in the zone file. This value is supplied in query responses to inform other servers how long they should keep the data in cache. The default value is <tt>1h</tt>.', max_length=16, validators=[orchestra.contrib.domains.validators.validate_zone_interval], verbose_name='min TTL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ttl',
            field=models.CharField(blank=True, help_text='Record TTL, defaults to 1h', max_length=8, validators=[orchestra.contrib.domains.validators.validate_zone_interval], verbose_name='TTL'),
        ),
    ]
