# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-03-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0005_auto_20200204_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
